### ISSUE TITLE
There is no changelog

### ISSUE THREAD

**Issue by doughsay** [nurugger07/inflex#81]
There is no changelog for this project, so I don't know what changed from 1.x to 2.0.  Is this upgrade safe?  Are there breaking changes?  I tried glancing through the commits, but can't really glean enough from them.

https://keepachangelog.com/en/1.0.0/

**Comment by nurugger07** [comment]
You are correct. There is no change log but also changes are very infrequent and minor. I highly recommend you review any library code prior to incorporating it into production code. I would even go so far as to say if you only need a portion of the functionality of a library you should implement the function yourself so that your code base is safe from changes. Feel free to use this library as an example for those implementations!
